### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by cfjedimaster** [bartosz-antosik/vscode-spellright#141]
Forgive the somewhat vague title, but all of a sudden, the extension seems to be broken for me. This is in the very latest Insiders Code.

In devtools I'm seeing this:

/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Activating extension 'ban.spellright' failed: Cannot read property 'Spellchecker' of null. (at Object.showMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:263))

Activating extension `ban.spellright` failed:  Cannot read property 'Spellchecker' of null (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:425:325)

Here is the error stack:  TypeError: Cannot read property 'Spellchecker' of null
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\lib\bindings.js:46:25)
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\lib\bindings.js:148:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:951)
	at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:761)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\src\spellright.js:21:18)
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\src\spellright.js:1944:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:951)
	at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:761)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\src\extension.js:14:20)
	at Object.<anonymous> (C:\Users\ray\.vscode-insiders\extensions\ban.spellright-2.2.14\src\extension.js:46:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:951)
	at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:761)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:702:454
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:702:566)
	at t._activateExtension (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:701:484)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:395)
	at e._activateExtension (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:425:188)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:424:757
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:424:732)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:423:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:759)
	at t.handleEagerExtensions (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:722:318)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:519
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.open (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:339)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:433
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at K.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:286
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:135:611
	at LOOP (fs.js:1757:14)
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9) (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:425:393)

**Comment by rakkarage** [comment]
ya after today's insider update it no longer shows eye icon on bar and no longer finds mistakes in md files though the commands are still in menu idk

thanks

**Comment by bartosz-antosik** [comment]
Hi! Thanks for notification. This was somehow expected. Detailed explanation can be found here [#20266](https://github.com/Microsoft/vscode/issues/20266). There are native dependencies which, once team decides to push ELECTRON shell layer version, need to be recompiled for 4 platforms. I am not always "on time" with this. They have been recompiled today and will be published very soon (today/tomorrow). Sorry for the trouble but it is hard to avoid sometimes also Insiders line is somehow experimental and may suffer from time to time.

**Comment by cfjedimaster** [comment]
Ah cool. No need to apologize - it makes perfect sense. Maybe add something short and sweet though to the readme?

**Comment by bartosz-antosik** [comment]
Should be fine in just published version 2.2.16.

**Comment by cfjedimaster** [comment]
FYI, I'm having this issue again with VSC Insider.

**Comment by bartosz-antosik** [comment]
Yes. Because Electron version has been bumped. Hope to resolve this soon.

**Comment by alberto-santini** [comment]
Hi, I am having the same problem on Code (OSS) 1.35.1, with Electron 4.1.4.

**Comment by phwuil** [comment]
Hello and same problem here on Code (OSS)  :-(

>Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-05T22:12:50.056Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 4.19.49-1-MANJARO
