### ISSUE TITLE
Stopped working in Insider

### ISSUE THREAD

**Issue by cfjedimaster** [bartosz-antosik/vscode-spellright#218]
I'm running Insider:

Version: 1.29.0-insider (user setup)
Commit: 5bd6ebe2dbc4dee510699020a25f70a69784ce8c
Date: 2018-10-09T09:31:07.090Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

And currently the spell check is no longer working and I'm not sure why. I see that it is ON in the UI. I'm in a markdown file. I don't see any weird settings either.

**Comment by cfjedimaster** [comment]
OS is Windows 10. (Sorry, I just assumed it was in the About text I had shared above.)

So I'm seeing some weirdness now. In this screen shot, you can see Vue marked as misspelled, which makes sense (I can add it to be ignored later):

![image](https://user-images.githubusercontent.com/393660/46700103-84bf2680-cbe1-11e8-86f5-96df52c42fb0.png)

But then I intentionally made a garbage word and it isn't marked as misspelled:

![image](https://user-images.githubusercontent.com/393660/46700128-93a5d900-cbe1-11e8-86fd-6436db49ef40.png)

**Comment by cfjedimaster** [comment]
FYI, for that messed up word, I even tried `plaay` and it didn't get marked up.

**Comment by bartosz-antosik** [comment]
I think it is exactly what I have described here: [#60394](https://github.com/Microsoft/vscode/issues/60394).

It seems there is some problem inside VSCode. You may want to try to see whether `Ctrl+.` works for the misspelled but not underlined words.

**Comment by cfjedimaster** [comment]
Ah ok - feel free to close this then. Thank you!

**Comment by bartosz-antosik** [comment]
Of course please upvote the issue! So far it seems to be ignored... ;-)

**Comment by PeteX** [comment]
Looks good here—thanks.

**Comment by cfjedimaster** [comment]
Same here - thank you!

**Comment by neilsustc** [comment]
Looks broken again...

Error from the dev console
```
ERR [spellright] Spell checker not initialized properly.
```

Version: 1.29.0-insider (user setup)
Commit: 2b06dd1ca31e407abed24f65e1804ae86180401d
Date: 2018-10-30T11:12:35.070Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

(And Windows 10 build 18267)

**Comment by bartosz-antosik** [comment]
Hm, interesting. Works for me, same version.

**Comment by neilsustc** [comment]
I tried to build your extension and got this

```
Activating extension `ban.spellright` failed:  Cannot find module 'glob'
extensionHostProcess.js:310
Here is the error stack:  Error: Cannot find module 'glob'
extensionHostProcess.js:310
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (c:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:771)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\zhang\Downloads\vscode-spellright-master\src\spellright.js:11:14)
	at Object.<anonymous> (C:\Users\zhang\Downloads\vscode-spellright-master\src\spellright.js:2343:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
```

**Comment by neilsustc** [comment]
This error is clearly located at

https://github.com/bartosz-antosik/vscode-spellright/blob/27ab307ac95306f4e26953dabd802e676a4643c3/lib/bindings.js#L51-L55

which means `defaultSpellcheck` is `null`. Then I searched `defaultSpellcheck =`. The only two occurrences are

https://github.com/bartosz-antosik/vscode-spellright/blob/27ab307ac95306f4e26953dabd802e676a4643c3/lib/bin/node-spellchecker/lib/spellchecker.js#L30

and

https://github.com/bartosz-antosik/vscode-spellright/blob/27ab307ac95306f4e26953dabd802e676a4643c3/lib/bindings.js#L59-L66

I added several `console.log` there and found they are never executed even though I can still get the `not initialized` error. Weird.
