### ISSUE TITLE
Extension fail to load

### ISSUE THREAD

**Issue by ivlis** [bartosz-antosik/vscode-spellright#269]
Spellright worked without problems, but since a few days ago it fails to load with an error.
VSCode version:

Version: 1.33.1
Electron: 4.1.1
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 5.0.7-arch1-1-ARCH

````
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'Spellchecker' of null
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/lib/bindings.js:46:25)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/lib/bindings.js:132:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/src/spellright.js:18:18)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/src/spellright.js:2341:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/src/extension.js:14:20)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/ban.spellright-3.0.38/src/extension.js:46:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:31:542)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:717:918
	at E._doActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:718:2)
	at E._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:716:772)
	at E.<anonymous> (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:714:224)
	at Generator.next (<anonymous>)
	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:176)
	at new Promise (<anonymous>)
	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:975)
	at Object.actualActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:713:946)
	at p._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:765)
	at define._activateExtensions.i.length.Promise.all.o.map.e (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:449)
	at Array.map (<anonymous>)
	at p._activateExtensions (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:437)
	at p.activateById (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:455:604)
	at E._activateById (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:715:497)
	at E.<anonymous> (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:723:542)
	at Generator.next (<anonymous>)
	at s (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:9)
````

**Comment by bartosz-antosik** [comment]
I belive you use Insiders version?

**Comment by bartosz-antosik** [comment]
How is it possible that you run Electron version 4.1.1? I have verified and neither regular nor Insiders version yet runs on Electron 4.x. The extenstion has binaries only for Electron version 3.x.

What version of VSCode you run?

**Comment by ivlis** [comment]
@bartosz-antosik I am running vscode-oss from archlinux repos. (https://www.archlinux.org/packages/community/x86_64/code/). It depends on the system-provided version of electron, which is 4.1.1. I tried to downgrade electron manually to 3.x, but vscode doesn't even start in that case.

**Comment by ivlis** [comment]
Any chance for fix?

**Comment by bartosz-antosik** [comment]
Yes, there is. I have already rebuilt binaries for most OSes but macOS. So give it please few days.

**Comment by mika-s** [comment]
I manually installed the latest version by cloning this repository inside *~/.vscode-oss/extensions/*. I also ran `npm install`. It seems to work so far.

**Comment by cfjedimaster** [comment]
Any update on this? I mean for an official release. On Windows it is still not working.

**Comment by bartosz-antosik** [comment]
It requires me updating binaries at least. I am under avalanche of jobs recently having very little time to spare on Spell Right. This situation will hopefully get better in few days.

**Comment by cfjedimaster** [comment]
Thank you - I appreciate your hard work!

**Comment by bartosz-antosik** [comment]
Hello thread! The recently uploaded version 3.0.46 should work with Electron 4.x. Please let me know in this thread if it does not or there are any issues. Thank you for your patience and sorry it has to wait - I am somehow busy recently.
