### ISSUE TITLE
Latest Insiders breaks Extension

### ISSUE THREAD

**Issue by cfjedimaster** [bartosz-antosik/vscode-spellright#367]
I noticed that the extension isn't working properly with the most recent Insider builds. First I noticed that no spell checking was being done. Then I noticed if I tried to run a command, like Open User Dictionary File, I'd get: 

    command 'spellright.openUserDictionary' not found

**Comment by cfjedimaster** [comment]
Saw this in console:

```
abstractExtensionService.ts:396 Activating extension 'ban.spellright' failed: Cannot read property 'Spellchecker' of null.
_logMessageInConsole @ abstractExtensionService.ts:396
```

**Comment by wincynty** [comment]
More from the Log (Extension Host) Output:

`[2020-05-22 18:57:50.129] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2020-05-22 18:57:50.133] [exthost] [error] TypeError: Cannot read property 'Spellchecker' of null
	at Object.<anonymous> (c:\Users\user\.vscode-insiders\extensions\ban.spellright-3.0.50\lib\bindings.js:46:25)
	at Module.o._compile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
	at Module.load (internal/modules/cjs/loader.js:816:32)
	at Module._load (internal/modules/cjs/loader.js:728:14)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:973:348)
	at Function.i._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:942:242)
	at Function.n._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:938:567)
	at Module.require (internal/modules/cjs/loader.js:853:19)
	at n (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\user\.vscode-insiders\extensions\ban.spellright-3.0.50\src\spellright.js:18:18)
	at Module.o._compile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
	at Module.load (internal/modules/cjs/loader.js:816:32)
	at Module._load (internal/modules/cjs/loader.js:728:14)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:973:348)
	at Function.i._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:942:242)
	at Function.n._load (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:938:567)
	at Module.require (internal/modules/cjs/loader.js:853:19)
	at n (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:524)
	at activate (c:\Users\user\.vscode-insiders\extensions\ban.spellright-3.0.50\src\extension.js:21:24)
	at Function._callActivateOptional (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:840:509)
	at Function._callActivate (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:840:160)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:960
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 7)`

**Comment by cfjedimaster** [comment]
It may be WSL2 related, as it seems to work right when running outside of that.
