### ISSUE TITLE
TypeError: Cannot read property '_documentData' of undefined

### ISSUE THREAD

**Issue by Eldaw** [bartosz-antosik/vscode-spellright#38]
When I go into Help -> Toggle Developer Tools, I see some errors.

shell.ts:423 Cannot read property '_documentData' of undefined: TypeError: Cannot read property '_documentData' of undefined
    at C:\Users\[Username]\.vscode\extensions\ban.spellright-1.1.4\src\spellright.js:170:35
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55038)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56829)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:392875
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55038)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56829)
    at t.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:348628)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
e.onUnexpectedError @ shell.ts:423
shell.ts:423 Cannot read property '_documentData' of undefined: TypeError: Cannot read property '_documentData' of undefined
    at C:\Users\[Username]\.vscode\extensions\ban.spellright-1.1.4\src\spellright.js:170:35
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55038)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56829)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:392875
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55038)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56829)
    at t.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:348628)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
e.onUnexpectedError @ shell.ts:423

**Comment by Eldaw** [comment]
If I clear all the errors, it comes back again when I select Spell Right in the list of my extensions.

**Comment by bartosz-antosik** [comment]
Thanks! It was too quick fix to quick fix #37. Should be fixed in 1.1.6.
