### ISSUE TITLE
Electron 11 / Apple Silicon Support

### ISSUE THREAD

**Issue by joeyboey** [bartosz-antosik/vscode-spellright#399]
This is my setup:

```
Version: 1.53.0-exploration
Commit: 2ca62929e9a439111ab08b871503cd50586b91c4
Date: 2020-12-25T06:28:52.403Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin arm64 20.3.0
SpellRight: 3.0.52
```

Right now SpellRight error out on every command with 'command not found'. I think is related to the missing binaries for Electron 11 and the arm64 architecture.

I did not find documentation on how to build all missing dependencies. If you provide some details about that I can try to build a working version. 

Thanks for your help!

**Comment by olivercrask** [comment]
I'm on 1.53.0-insiders and experiencing the same issue. Though I'm on a Windows 10 and not on any sort of silicon hardware!

**Comment by olivercrask** [comment]
Tested on vscode 1.52.1 without issue so seems to be due to the 1.53 update.

**Comment by joeyboey** [comment]
I'll downgrade tomorrow and take a look.

**Comment by bartosz-antosik** [comment]
Hi, this is due to Electron version bump (10.x to 11.x). I will probably have some time next week to compile binary dependencies. This currently only touches Insiders preview, I hope. It happens every time when VSCode creators decide to upgrade Electron in Insiders version. Happy New Year!

**Comment by joeyboey** [comment]
Hey @bartosz-antosik, is there any update on this issue?

**Comment by bartosz-antosik** [comment]
I was wrong! The binaries for Electron 11 have already been updated few days ago. But I have no way for now to compile the binaries for Apple ARM architecture. I will keep looking around.

**Comment by joeyboey** [comment]
Do you have instructions on how to do that somewhere? I can do that :)

**Comment by joeyboey** [comment]
Hey, are there instructions somewhere?

**Comment by joeyboey** [comment]
Hey @bartosz-antosik, are there any updates?

**Comment by bartosz-antosik** [comment]
@joeyboey I am sorry I am truly loaded with other things recent days. I will prepare you some instructions on how to create appropriate binaries. It will however require rebuilding them with each major Electron version bump. That is about each couple of months.

**Comment by bartosz-antosik** [comment]
@joeyboey Thank you. I will try to be quick with the batches & some instruction on how to do this.

**Comment by joeyboey** [comment]
Hey I already tried to to a little bit.
I bumped electron to version `11.3, vscode does run with npm run test but closes after 20 seconds. The console shows a lot of `ECONNREFUSED` error messages to localhost. (Vscode also runs with every other extension activated, I don't know if that's the problem).

I'll try to dig in a little later to fix the problems...

**Comment by bartosz-antosik** [comment]
@joeyboey Most probably the problem is that extension is missing binary dependencies compiled on Apple silicone. So the point is that you may try to clone the project, go to `/lib/bin/node-spellchecker/`, update dependencies (`npm install`), install node-gyp (`npm install -g node-gyp`) and try to run `build-macos-apple.sh` script. It should build the binary dependencies and copy them to `bin` folder above with names like `spellchecker-darwin-apple-11.1.0-x64.node`.

**Comment by joeyboey** [comment]
So everything went fine from the build perspective. As far as I could notice every dependency was built correctly.

The first start of vscode held on pretty long, but as soon as I tried to load up a `tex` document it crashed (but I don't think that that was the reason). The following attempts quit much earlier, after about 15 seconds.

I disabled all extensions beforehand to minimize any issues.

I did also run all non breaking audit suggestions from npm. If it helps I could start with a clean repo.
Unfortunately I don't have much expertise in code extension, but fortunately I develop a lot with node.js :)

I attached the error log:

```zsh
❯ npm run test

> spellright@3.0.56 test
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###

Current working directory: /Users/joe/git/vscode-spellright
Found .vscode-test/vscode-1.54.1. Skipping download.
Running extension tests: /Users/joe/git/vscode-spellright/.vscode-test/vscode-1.54.1/Visual Studio Code.app/Contents/MacOS/Electron /Users/joe/git/vscode-spellright/test --extensionDevelopmentPath=/Users/joe/git/vscode-spellright --extensionTestsPath=/Users/joe/git/vscode-spellright/test --locale=en
[main 2021-03-11T15:14:09.801Z] update#setState idle

(node:92852) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(anon):setopt:7: can't change option: monitor



[ERROR]: gitstatus failed to initialize.



  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh

(node:92858) Electron: Loading non-context-aware native module in renderer: '/Users/joe/git/vscode-spellright/.vscode-test/vscode-1.54.1/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

2021-03-11 16:14:12.112 Code Helper (Renderer)[92858:1483672] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-03-11 16:14:12.112 Code Helper (Renderer)[92858:1483672] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.

2021-03-11 16:14:12.119 Code Helper (Renderer)[92858:1483672] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

(node:92852) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(node:93167) Electron: Loading non-context-aware native module in renderer: '/Users/joe/git/vscode-spellright/.vscode-test/vscode-1.54.1/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

(node:92852) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(node:93170) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Tests exited with code: 1
``

**Comment by bartosz-antosik** [comment]
@joeyboey Did the binaries (`spellchecker-darwin-apple-11.1.0-x64.node`, there should be two of them with varying version numbers) built correctly?

**Comment by joeyboey** [comment]
I got those in `lib/bin/`:

```zsh
spellchecker-darwin-11.1.0-x64.node
spellchecker-darwin-6.0.9-x64.node
spellchecker-darwin-7.1.7-x64.node
spellchecker-darwin-9.1.0-x64.node
```

**Comment by joeyboey** [comment]
However I chose electron 11.3, should I downgrade to 11.1?

**Comment by bartosz-antosik** [comment]
@joeyboey Those are original, they will not work with Apple Silicone. The sh file I have mentioned should build new binaries. The Electron version is not the point - every binary built for Electron 11.x will work as long as major version number does not change.

Have you started the `build-macos-apple.sh` script? Was the output about correct? There should be no red error messages and it should end with a green (if I remember correctly) OK. As a result in the folder above where the script resides there should be new binaries as mentioned above.

**Comment by joeyboey** [comment]
oops I forgot to pull, I used the old build script.

now I got:

```zsh
spellchecker-darwin-apple-11.1.0-x64.node
spellchecker-darwin-apple-9.1.0-x64.node
```

Still the same deprecation warnings and the GitHub error at the start.

**Comment by bartosz-antosik** [comment]
@joeyboey Oh, so you DO have the binaries!

I have absolutely no idea what are those deprecation & GitHub warnings. What I would do is that I would put those binaries to a folder where they belong in regular installation and test whether the extension starts.

**Comment by joeyboey** [comment]
So I tried a few different things:

- I didn't find any information on how to just install the binaries, I figured that only placing them inside the existing spell right extension dir would really help
- when I copied the whole repository to the extension folder, code did not even load anything (maybe because of the missing token?)
- then I just replaced everything from the "official" spell right folder with the contents of my cloned repo. Sadly the same error (`COMMAND NOT FOUND` for everything regarding Spell Right). The last thing I tried was also replacing the old darwin-x64 binaries with the apple ones, but that did not help either.

This is what I found in the exthost.log:

```shell
[2021-03-12 09:22:33.918] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2021-03-12 09:22:33.919] [exthost] [error] TypeError: Cannot read property 'Spellchecker' of null
    at Object.<anonymous> (/Users/joe/.vscode/extensions/ban.spellright-3.0.56/lib/bindings.js:46:25)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12841)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Function.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
    at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
    at Function.W._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12287)
    at Object.<anonymous> (/Users/joe/.vscode/extensions/ban.spellright-3.0.56/src/spellright.js:18:18)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12841)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Function.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
    at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
    at Function.W._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12287)
    at activate (/Users/joe/.vscode/extensions/ban.spellright-3.0.56/src/extension.js:21:24)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:14037)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:13714)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11746
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
```

**Comment by tobydriscoll** [comment]
I'm in the same boat (darwin on amd64). The problem is at loading the binary in bindings.js. 

For one thing, it's looking for node files with 'amd64' in the name, not 'x64'. But even when I renamed the files built from cloning the repo, and ensured it was trying to load them, the require statement errors and no binary is loaded.

**Comment by opeik** [comment]
Having the same issues on my M1 Mac mini.

**Comment by milind** [comment]
Hey @joeyboey! Was just wondering whether you might have any updates on this? Been looking for a good grammar/spellchecker for my markdown notes if you might have found an alternative as well. Thanks!

**Comment by joeyboey** [comment]
@milind Sorry, no updates on that.

**Comment by rbubley** [comment]
I don't know if this is the same issue or a different one, as things may have moved on. Spellright is still not starting up on macOS/Apple Silicon:

Environment:
```
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```

And the logs show:
```
[2021-12-08 10:41:56.146] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2021-12-08 10:41:56.146] [exthost] [error] TypeError: Cannot read property 'Spellchecker' of null
	at Object.<anonymous> (/Users/russ/.vscode/extensions/ban.spellright-3.0.60/lib/bindings.js:46:25)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
	at Function.h._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/russ/.vscode/extensions/ban.spellright-3.0.60/src/spellright.js:18:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
	at Function.h._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at activate (/Users/russ/.vscode/extensions/ban.spellright-3.0.60/src/extension.js:21:24)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:15210)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14883)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13080
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
	at async w.$activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:20503)
```

**Comment by tkrunning** [comment]
I'm also getting the same error on an Apple Silicon Mac:

```
Activating extension 'ban.spellright' failed: Cannot read property 'Spellchecker' of null.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:577
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
P @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

It doesn't seem to activate, and I'm running the latest version (`v3.0.60`), and my VS Code is also at the latest version (as someone mentioned as a fix in another thread):

```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```

**Comment by cdbattags** [comment]
Same issue for me as @tkrunning! Would love to help out however I can.
