### ISSUE TITLE
Crash on latest insiders

### ISSUE THREAD

**Issue by Queuecumber** [bartosz-antosik/vscode-spellright#425]
Using insiders from 2021-04-21 the extension fails to activate with the following error, this could be a regression in the nightly vscode or it could be an intentional change to the extension API I'm not sure:

```
[2021-04-21 09:30:32.251] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2021-04-21 09:30:32.255] [exthost] [error] TypeError: Cannot read property 'Spellchecker' of null
	at Object.<anonymous> (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.56/lib/bindings.js:46:25)
	at Module.u._compile (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:1311)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.r._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27794)
	at Function._._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24510)
	at Function.a._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:59184)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.56/src/spellright.js:18:18)
	at Module.u._compile (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:1311)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.r._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27794)
	at Function._._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24510)
	at Function.a._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:59184)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:694)
	at activate (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.56/src/extension.js:21:24)
	at Function._callActivateOptional (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:14805)
	at Function._callActivate (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:14474)
	at /opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:12626
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

**Comment by Queuecumber** [comment]
based on my reading of the code it looks like it can't load the bindings but I'm not sure why

**Comment by Queuecumber** [comment]
Adding some log options reveals the error:

```
[Extension Host] [spellright] Error: The module '/home/max/.vscode-insiders/extensions/ban.spellright-3.0.56/lib/bin/spellchecker-deb-11.1.0-x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). (at /home/max/.vscode-insiders/extensions/ban.spellright-3.0.56/lib/bindings.js:32:15)
```

so those binding files will need to be updated for the latest insiders it looks like

**Comment by Queuecumber** [comment]
@bartosz-antosik I'm curious if this project should be considered abandoned, there's been no update in some time and a number of issues and PRs are left unanswered

**Comment by Queuecumber** [comment]
I managed to figure out how to rebuild the spellchecker module to work on the version of electron that vscode insiders uses (which is the source of the module version 87 mismatch). I'm leaving the compiled binary here in case other people run into this issue and need it, it is for linux x64.

Find the binary and instructions on [this gist](https://gist.github.com/Queuecumber/053e1d6fedc4da2e7e58dc23ee736889)

Copy the binary from that gist to `${HOME}/.vscode-insiders/extensions/ban.spellright-3.0.56/lib/bin` and reload vscode and the extension should start working again.

**Comment by Queuecumber** [comment]
Based on the response to #426 I think this can be closed correct?
