### ISSUE TITLE
Could not enable in remote Linux machine

### ISSUE THREAD

**Issue by siamumar** [bartosz-antosik/vscode-spellright#485]
It works find on MacOS. I installed and enabled in on a remote Linux machine that I access via SSH. I also installed the dictionaries (English) as mentioned in the ReadMe. However, I still could not make it work. 

First, there is no spellright icon in the status bar similar to what I see on MacOS (it's not even in the menu that appears on right-click).

I tried to enable it from command pallet but received the error "Command 'SpellRight: Turn OFF for Current Document Type' resulted in an error (command 'spellright.setCurrentTypeOFF' not found)"

I also tried adding following to my setting.json

```
	"spellright.language": [
		"en"
	],
	"spellright.documentTypes": [
		"markdown",
		"latex",
		"plaintext"
	],
```

I installed hunspell-en. But that did not help either.

**Comment by george-kuanli-peng** [comment]
I have the same problem, too.

**Comment by JunCEEE** [comment]
The same here. I didn't see the spellright icon in the status bar as well on my remote centos Linux machine. When I tried the `SepllRight: Select dictionary` command from the command pallet, it raised a "command not found" error as shown in the screenshot:
![image](https://user-images.githubusercontent.com/3163505/154247901-64cfff0e-6f65-4921-9b3b-80ddcf7574f0.png)

Any solution or workaround?

**Comment by rlh1994** [comment]
I am also getting this issue, using a chromebook with the linux container. Extension host logs:

`Linux penguin 5.10.110-15808-ge5740beba59b #1 SMP PREEMPT Tue May 24 10:51:11 PDT 2022 aarch64 GNU/Linux`
```
[2022-06-18 10:45:20.947] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2022-06-18 10:45:20.947] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/home/rlhill128/.vscode/extensions/ban.spellright-3.0.64/lib/bindings.js:46:25)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
	at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61578)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at _ (/usr/share/code/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/rlhill128/.vscode/extensions/ban.spellright-3.0.64/src/spellright.js:18:18)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
	at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61578)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at _ (/usr/share/code/resources/app/out/vs/loader.js:4:699)
	at activate (/home/rlhill128/.vscode/extensions/ban.spellright-3.0.64/src/extension.js:21:24)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17470)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17131)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:14945
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
```
