### ISSUE TITLE
Not Working on Latest Insiders Build

### ISSUE THREAD

**Issue by Queuecumber** [bartosz-antosik/vscode-spellright#489]
My guess is that they updated the electron version again. Error is:

```
[2022-02-23 08:36:50.606] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.60/lib/bindings.js:46:25)
	at Module.u._compile (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.n._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
	at Function.b._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
	at Function.g._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.60/src/spellright.js:18:18)
	at Module.u._compile (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.n._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
	at Function.b._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
	at Function.g._load (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/opt/visual-studio-code-insiders/resources/app/out/vs/loader.js:4:699)
	at activate (/home/max/.vscode-insiders/extensions/ban.spellright-3.0.60/src/extension.js:21:24)
	at Function._callActivateOptional (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:16082)
	at Function._callActivate (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:15747)
	at /opt/visual-studio-code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:13571
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 3)
	at async Promise.all (index 0)
```

I remember I fixed this by manually compiling the binaries last time it happened but I can't remember how I did it anymore. 

Is this project even still being maintained? There are a lot of issues and PRs to merge but I havent seen any activity since October. If regular maintenance isnt something thats happening there should probably be a push to get #280 merged.

**Comment by le-bananafish** [comment]
I have noticed that Spellright is no longer working. The language indicator on the bottom bar no longer appears.

I don't have normal VS Code to check if it's fine there.

Yea, from what I can tell, this project is kinda dead, which is a shame since Spell Right is actually pretty great. Does this extension rely on (a) specific version(s) of Electron?

**Comment by MichaelKuhl71** [comment]
Today a got a VS code update an I get the same error

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Datum: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
Betriebssystem: Windows_NT x64 10.0.19043


```bash
[2022-03-31 12:54:23.956] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2022-03-31 12:54:23.956] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\xxxx\.vscode\extensions\ban.spellright-3.0.60\lib\bindings.js:46:25)
	at Module.u._compile (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:32156)
	at Function.E._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:28749)
	at Function.g._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\xxxx\.vscode\extensions\ban.spellright-3.0.60\src\spellright.js:18:18)
	at Module.u._compile (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:32156)
	at Function.E._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:28749)
	at Function.g._load (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at activate (c:\Users\xxxx\.vscode\extensions\ban.spellright-3.0.60\src\extension.js:21:24)
	at Function._callActivateOptional (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:16070)
	at Function._callActivate (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:15731)
	at c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:13549
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8096)
	at async g._initialize (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7460)
```
