### ISSUE TITLE
No longer working as of VS Code version 1.66.0

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [bartosz-antosik/vscode-spellright#500]
I updated Visual Studio Code to version 1.66.0, and none of the functionality works anymore. No misspelled words are detected, and no errors or warnings are created.

**Comment by SR--** [comment]
Same here. Might be a VSCode problem as this release has a few other issues...

But it would be great to have spellright back as it is in daily use (thanks a lot!).

**Comment by Luk164** [comment]
Same here, I was wondering what happened.

**Comment by mcrossley** [comment]
I get the following error in the Extension Host Log...

[2022-04-02 12:11:28.501] [exthost] [error] Activating extension ban.spellright failed due to an error:
[2022-04-02 12:11:28.501] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\mcrossley\.vscode\extensions\ban.spellright-3.0.60\lib\bindings.js:46:25)
	at Module.u._compile (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:32156)
	at Function.E._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:28749)
	at Function.g._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\mcrossley\.vscode\extensions\ban.spellright-3.0.60\src\spellright.js:18:18)
	at Module.u._compile (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:32156)
	at Function.E._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:28749)
	at Function.g._load (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at activate (c:\Users\mcrossley\.vscode\extensions\ban.spellright-3.0.60\src\extension.js:21:24)
	at Function._callActivateOptional (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:16070)
	at Function._callActivate (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:15731)
	at c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:13549
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8096)
	at async g._initialize (c:\Users\mcrossley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7460)

**Comment by AceTheWiz** [comment]
Here is an alternative. valentjn.vscode-ltex

**Comment by Luk164** [comment]
> Here is an alternative. `valentjn.vscode-ltex`. Just paste the Id into VSCode's extensions search box. Customise your language by using the `Ltex: Language` setting.

Reverting to older version also works.

**Comment by reduckted** [comment]
I think this is caused by VS Code updating to Electron 17: https://code.visualstudio.com/updates/v1_66#_electron-17-update

This has happened before in  https://github.com/bartosz-antosik/vscode-spellright/issues/443#issuecomment-895189037

**Comment by SR--** [comment]
ltex dictionary seems too limited by comparison, it struggles with names, technical terms, academic terms, all that. try 'bioreceptivity'. it does not support multi-language documents either, it seems...

so, keen to have this fixed

**Comment by MikeMcC399** [comment]
I reverted VS Code to 1.65.2 (system setup) on Windows 11 and Spell Right worked again. I could confirm that upgrading to 1.66.0 stopped Spell Right working. There was no spelling option down the bottom.

I find the same error as @mcrossley posted in https://github.com/bartosz-antosik/vscode-spellright/issues/500#issuecomment-1086617733

```
[exthost] [error] Activating extension ban.spellright failed due to an error:
[exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
```

Thanks to you all for posting! I was really wondering what had gone wrong on my system.

**Comment by MikeMcC399** [comment]
Should this issue also be reported in https://github.com/microsoft/vscode/issues? I couldn't find it there.

**Comment by dpoves** [comment]
I have seen that the updates for the project are far in between and no activity by @bartosz-antosik since October. I hope the developer is alright. This extension is incredibly useful. @MikeMcC399 I guess it wouldn't hurt to make them aware.

**Comment by Luk164** [comment]
Are there any other collaborators allowed to work on this? I know we could always fork it but that would complicate everything a lot. Hope he is ok.

**Comment by MikeMcC399** [comment]
- This issue looks very similar to https://github.com/bartosz-antosik/vscode-spellright/issues/425

According to the release notes https://code.visualstudio.com/updates/v1_66#_engineering

"What does this change mean for VS Code users?

Operations like switching workspaces and reloading workspaces should now be faster. With this update, we also bump our Chromium version to 98.0.4758.109 and Nodejs version to 16.13.0."

Does anybody know how to generate a log like @Queuecumber showed in https://github.com/bartosz-antosik/vscode-spellright/issues/425#issuecomment-824084424? This referenced an issue with a mismatch of `NODE_MODULE_VERSION`.

**Comment by bartosz-antosik** [comment]
Hello everyone! Author here. I am sorry, for the trouble. Extension has binary dependencies which have to be updated with every major update of the version of Electron environment which VSCode is built with. Sometimes this goes smoother, sometimes it is more complicated, like whern it rapidly changes between Insiders and Regular build. The update with new binaries (3.0.62) has been published, so it should be working for now. I am still very short on time to work more on the extension. Foremost, I do not have an Apple Silicone Mac (M1) around, to rebuild the binaries for it's architecture...

**Comment by MikeMcC399** [comment]
@bartosz-antosik 
Many thanks for the update! I can confirm that Spell Right 3.0.62 is working with VSCode 1.66.0 on Windows 11.

**Comment by kashanico** [comment]
@bartosz-antosik any workarounds for those with Apple Silicone?
