### ISSUE TITLE
Activating extension ban.spellright failed (MacOS M1)

### ISSUE THREAD

**Issue by kashanico** [bartosz-antosik/vscode-spellright#502]
I am on MacOS (M1) with the latest version of VS Code and SpellRight, when I start VS Code the extension fails to load with the following error. Any ideas?

```
[2022-04-18 16:07:03.179] [exthost] [error] Activating extension ban.spellright failed due to an error:

[2022-04-18 16:07:03.179] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/lib/bindings.js:46:25)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32156)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28749)
	at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/src/spellright.js:18:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32156)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28749)
	at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at activate (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/src/extension.js:21:24)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:16070)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:15731)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:13549
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8096)
	at async g._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)
```

**Comment by kashanico** [comment]
https://github.com/bartosz-antosik/vscode-spellright/issues/500

**Comment by borekb** [comment]
@bartosz-antosik, you noted in https://github.com/bartosz-antosik/vscode-spellright/issues/500#issuecomment-1090035129 that you don't have access to an M1 hardware. Is there something people with M1 chips could do to help you? I have zero experience building native modules but if you give me instructions, I'll be happy to do that.

Some more options:

- https://www.scaleway.com/en/hello-m1/
- GitHub Actions might get M1 support:
    - https://github.com/actions/virtual-environments/issues/2187
    - https://github.com/actions/runner/issues/805

**Comment by borekb** [comment]
Fighting with Python at the moment (good old Python 2 vs. Python 3 vs. newer macOS and Homebrew and ...) but I hope I'll win, eventually 😄.

**Comment by bartosz-antosik** [comment]
@borekb Thought Apple with M1 is free of such hassle!

**Comment by borekb** [comment]
I'm losing the battle; if anyone wants to take a look: PR https://github.com/bartosz-antosik/vscode-spellright/pull/503.

**Comment by bartosz-antosik** [comment]
@borekb Thanks! Now if you could tell me whether just pushed update 3.0.64 works for you would be appreciated. Also, if you could maybe watch Insiders build of VSCode and make similar update for new versions of Electron that usually make first appearance there, would make it much smoother!

**Comment by borekb** [comment]
🎉 works out of the box with **3.0.64**.

As for newer / Insider versions, what should I do? Go to the **About** dialog and find the version there? Currently, Insiders is on Electron **17.4.0**:

<img width="340" alt="Screen Shot 2022-04-22 at 8 36 01" src="https://user-images.githubusercontent.com/101152/164617339-ec3c3e37-804d-4a84-9ef2-45db418705f4.png">

But the source files say **17.4.1**:

https://github.com/microsoft/vscode/blob/72b4be55fad0d41092d7df8e03b5597c715fd2e2/package.json#L138

I guess this will be changing quite frequently? Also, why is version **13.1.7** being built?

https://github.com/bartosz-antosik/vscode-spellright/blob/bcfbb009ae0fa2731156fb994d6c23a83ce46f03/lib/bin/node-spellchecker/build-macos-apple.sh#L5

**Comment by borekb** [comment]
Maybe a broader question: is it still necessary to use a (fork of) https://www.npmjs.com/package/spellchecker? Electron has a built-in spell checker since version 8, what's your opinion on using that?

**Comment by bartosz-antosik** [comment]
@borekb It does not change very often. About twice per year. Version 13 is built, because it was in regular release just moments ago. So I thought it is safe to have at least two overlapping versions.

I do not know much about the spellchecker built inside Electron and whether it serves some API. Will have to examine this but If I have some time to push Spell Right forward I would rather start with turning it into Language Server which is long overdue.

**Comment by borekb** [comment]
Are you watching the Insider releases yourself? If you open a PR with binaries for platforms you can build yourself & ping me, I'll be happy to generate the arm64 / M1 binaries as well. I can't promise I'll be very proactive about this myself (would love to but I'll almost certainly forget to be honest 😄).

**Comment by borekb** [comment]
VSCode 1.69 has new Electron version again, binaries can be downloaded from PR #515 (until new Spell Right release is created; the current one is 3.0.64).
