### ISSUE TITLE
Extension does not start (Windows 10, VSCode 1.69)

### ISSUE THREAD

**Issue by klausj1** [bartosz-antosik/vscode-spellright#513]
I am not 100% sure, but I think after the latest VSCode update spellright does no start anymore.

VSCode Information:
```
Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042

```
Spell Right: `V3.0.64`

Error message (log of extension host):
```
[2022-07-08 16:48:17.502] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\userName\.vscode\extensions\ban.spellright-3.0.64\lib\bindings.js:46:25)
	at Module.u._compile (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32133)
	at Function.v._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:28715)
	at Function.b._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\userName\.vscode\extensions\ban.spellright-3.0.64\src\spellright.js:18:18)
	at Module.u._compile (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32133)
	at Function.v._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:28715)
	at Function.b._load (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at activate (c:\Users\userName\.vscode\extensions\ban.spellright-3.0.64\src\extension.js:21:24)
	at Function._callActivateOptional (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17470)
	at Function._callActivate (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17131)
	at c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b._activate (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8180)
	at async b._waitForDepsThenActivate (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8122)
	at async b._initialize (c:\Users\userName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7486)
```

**Comment by borekb** [comment]
Same issue on macOS, will try to regenerate an M1 build by following https://github.com/bartosz-antosik/vscode-spellright/pull/503.

**Comment by RoyiAvital** [comment]
I have the same issue with VS Codium `1.69`.

**Comment by zjj0930** [comment]
The same problem occurs to me as well.

```
Version: 1.69.0 (system setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```
> Spell Right: V3.0.64

**Comment by ok11** [comment]
The extension does not start after the latest VSC update: 

```
Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043
```

Diagnostic:

`mainThreadExtensionService.ts:111 Activating extension 'ban.spellright' failed: Cannot read properties of null (reading 'Spellchecker').`

**Comment by c3er** [comment]
Seems independent of OS. I have the same error on Ubuntu.

```
Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T08:29:47.439Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.13.0-52-generic snap
```

Error in log:

```
[2022-07-12 11:55:13.783] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/home/c3er/.vscode/extensions/ban.spellright-3.0.64/lib/bindings.js:46:25)
	at Module.u._compile (/snap/code/100/usr/share/code/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/snap/code/100/usr/share/code/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/c3er/.vscode/extensions/ban.spellright-3.0.64/src/spellright.js:18:18)
	at Module.u._compile (/snap/code/100/usr/share/code/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/snap/code/100/usr/share/code/resources/app/out/vs/loader.js:4:699)
	at activate (/home/c3er/.vscode/extensions/ban.spellright-3.0.64/src/extension.js:21:24)
	at Function._callActivateOptional (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17470)
	at Function._callActivate (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17131)
	at /snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b._activate (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async b._waitForDepsThenActivate (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async b._initialize (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

**Comment by reduckted** [comment]
This has happened before in #443 and #500. 

The latest version of VS Code updated Electron and Node, which breaks this extension.
https://code.visualstudio.com/updates/v1_69#_electron-18-update

**Comment by klausj1** [comment]
Version 3.0.72 is working for me now :)

**Comment by bartosz-antosik** [comment]
The binary dependencies have been rebuilt. Thanks @borekb for rebuilding Apple Silicon dependencies. Also thanks to @nkuehn, who proposed to rebuild the binaries using GitHub Actions which is now implemented and should smoothly generate binaries for Windows/Linux/Macos on future Electron's version changes. It has limitations though: 1) Macos is only for Intel based machines 2) Linux is built on Ubuntu based VM so I have doubts whether it will work in other distributions (glibc version may vary also symbol tagging/versioning in glibcc may conflict).

BUT:

If anyone could check whether the extension works with RHEL rooted distributions (e.g. Fedora?) I would be very grateful!

**Comment by pvdstel** [comment]
v3.0.72 works on Windows 10 / VSCode 1.69.1 🎉

**Comment by nkuehn** [comment]
v3.0.72 works on macOS Monterey (arm64). Thank you for continuing to maintain spellright!

**Comment by AVAtarMod** [comment]
> If anyone could check whether the extension works with RHEL rooted distributions (e.g. Fedora?) I would be very grateful!

@bartosz-antosik, On Fedora 36 extension doesn't work. I use VSCodium.
More info about VSCodium:
Version: 1.72.1
Release: 22284
Commit: f39747598a53ebfc7454599bb310a2ffe4e4ce68
Date: 2022-10-11T18:20:14.732Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.14-200.fc36.x86_64
Sandboxed: No

**Comment by reduckted** [comment]
VS Code updated to Electron 22 and this bug is now happening again.
https://code.visualstudio.com/updates/v1_78#_electron-22-update

Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

```
[error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\username\.vscode\extensions\ban.spellright-3.0.112\lib\bindings.js:46:25)
```
