### ISSUE TITLE
No spellingchecking after Code update: Activating extension ban.spellright failed due to an error: bindings.js:46:25

### ISSUE THREAD

**Issue by Ben-Voris** [bartosz-antosik/vscode-spellright#551]
After an update to this:

```text
Version: 1.78.0 (system setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

Spellright v3.0.112 stopped checking all languages, including plaintext and markdown. 
Entries from exthost.log

```text
2023-05-08 11:30:22.560 [info] ExtensionService#_doActivateExtension ban.spellright, startup: false, activationEvent: 'onStartupFinished'
...
2023-05-08 11:30:23.263 [error] Activating extension ban.spellright failed due to an error:
2023-05-08 11:30:23.263 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\BVoris\.vscode\extensions\ban.spellright-3.0.112\lib\bindings.js:46:25)
	at u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
	at h._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
	at I._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\BVoris\.vscode\extensions\ban.spellright-3.0.112\src\spellright.js:18:18)
	at u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
	at h._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
	at I._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at activate (c:\Users\BVoris\.vscode\extensions\ban.spellright-3.0.112\src\extension.js:19:24)
	at kn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:14705)
	at kn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:14409)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:12432
	at async v.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6644)
	at async v.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6607)
	at async v.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6064)
```

Here are all of my spellright settings.

```jsonc
 "spellright.spellContextByClass": {
    "jsonc": "comments",
    "c": "comments strings",
    "cpp": "comments strings",
    "tal": "comments strings",  // See https://github.com/knovichikhin/vscode_tal/issues/24
    "tacl": "comments strings"  // See https://github.com/knovichikhin/vscode_tal/issues/24
  },
  "spellright.language": [
    "en"
  ],
  "spellright.addToSystemDictionary": true,
  "spellright.notificationClass": "information",
  "spellright.documentTypes": [
    "jsonc",
    "markdown",
    "plaintext",
    "shellscript",
    "c",
    "cpp",
    "tal",  // See https://github.com/knovichikhin/vscode_tal/issues/24
    "tacl", // See https://github.com/knovichikhin/vscode_tal/issues/24
    "git-commit",
    "HTML",
    "html"
  ],
  "spellright.ignoreRegExpsByClass": {
    "markdown": [
      "/&amp;/g",
      "/&nbsp;/g"
    ],
    "cpp": [
      "/#include\\s+\\\".+\\\"/g"
    ],
    "html": [
      "/&amp;/g",
      "/&nbsp;/g"
    ]
  },
```

**Comment by bartosz-antosik** [comment]
Thanks for the report. I am addressing it just now. Excuse me, have somehow missed Electron version update. It requires rebuild of binary dependencies.

**Comment by epsonlq138** [comment]
Thank you so much. It work well now.

**Comment by Ben-Voris** [comment]
> Thanks for the report. I am addressing it just now. Excuse me, have somehow missed Electron version update. It requires rebuild of binary dependencies.

Thanks for the quick response.
