### ISSUE TITLE
[Bug] The extension stopped working with VS Code 1.82

### ISSUE THREAD

**Issue by walpox** [bartosz-antosik/vscode-spellright#561]
The affected versions are for the 64-bit architecture on Windows 10:

- Visual Studio Code: 1.82.0.
- VSCodium: 1.82.0.23250.

The extension used to display an eye icon on the status bar. After updating VSCode/VSCodium to these versions, the eye no longer shows up and it seems the extension just stopped working.

In VSCodium, I noticed the runtime status of the extension shows as "Not yet activated".

![2023-09-09-WyYccB](https://github.com/bartosz-antosik/vscode-spellright/assets/68171111/cf80f1c4-d1a9-4532-9482-46560bdb9ba8)

**Comment by walpox** [comment]
I downgraded VSCodium to version 1.81.1.23222 and the extension began working fine.

**Comment by phire** [comment]
Error from the Extension Host output:

```
2023-09-09 13:36:07.471 [error] Activating extension ban.spellright failed due to an error:
2023-09-09 13:36:07.479 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
    at Object.<anonymous> (/Users/phire/.vscode/extensions/ban.spellright-3.0.116/lib/bindings.js:46:25)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
    at Function.m._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
    at Function.D._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
    at Module.apply (node:internal/modules/cjs/loader:1195:19)
    at Module.require (/Users/phire/.vscode/extensions/github.copilot-1.110.389/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/phire/.vscode/extensions/ban.spellright-3.0.116/src/spellright.js:18:18)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
    at Function.m._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
    at Function.D._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
    at Module.apply (node:internal/modules/cjs/loader:1195:19)
    at Module.require (/Users/phire/.vscode/extensions/github.copilot-1.110.389/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at activate (/Users/phire/.vscode/extensions/ban.spellright-3.0.116/src/extension.js:19:24)
    at Function.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:13032)
    at Function.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:12750)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10857
    at E.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6206)
    at E.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6169)
    at E.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:5626)
```

**Comment by devcops-consulting** [comment]
Same in here:

The issue:
```powershell
2023-09-10 12:34:56.204 [error] Activating extension ban.spellright failed due to an error:
2023-09-10 12:34:56.204 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\Mikáczó Péter\.vscode\extensions\ban.spellright-3.0.112\lib\bindings.js:46:25)
	at u._compile (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at c._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\Mikáczó Péter\.vscode\extensions\ban.spellright-3.0.112\src\spellright.js:18:18)
	at u._compile (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at c._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at activate (c:\Users\Mikáczó Péter\.vscode\extensions\ban.spellright-3.0.112\src\extension.js:19:24)
	at Y.eb (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:13032)
	at Y.db (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:12750)
	at c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:10857
	at async E.n (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:6206)
	at async E.m (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:6169)
	at async E.l (c:\Users\Mikáczó Péter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:5626)
```

I tried with latest and previously versino as well.

I'm using custom dictionaries as well

VSCode version:
```bash
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by wpdevelopment11** [comment]
As a workaround until author will update the extension for the new version of Electron,
you can do this:

1. Get the `.node` binary file [from here](https://github.com/wpdevelopment11/vscode-spellright/tree/main/lib/bin) for your arch and OS.
2. Open Command Palette in vscode and run "Open Extension folder".
3. Drop the binary to `ban.spellright-3.0.116/lib/bin`
4. Enjoy.

Tested only on Windows.

**Comment by ch-e-mistry** [comment]
Thank you @wpdevelopment11 , works fine. Also on Windows(11).

**Comment by bartosz-antosik** [comment]
Hi! There is new version released, which should work with newer version of VSCode. The extension has binary dependencies and they have to be rebuilt at each bump of the Electron. It takes a while, especially because I do not have a Mac with Mx chip around. Sorry for the problem but there is no better way of doing this currently.
