### ISSUE TITLE
Doesn't seem to work on VSCode 1.88.0

### ISSUE THREAD

**Issue by rotemdan** [bartosz-antosik/vscode-spellright#573]
After upgrading to `1.88.0`, the extension doesn't seem to work anymore. I'm not seeing any suggestions or corrections, or icons on the status bar.

Here is my detailed version information:
```
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by c3er** [comment]
Stopped also working for me.

My version information:

```
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

My exthost.log:

```
2024-04-06 16:15:08.572 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/Users/c3er/.vscode/extensions/ban.spellright-3.0.122/lib/bindings.js:46:25)
	at o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/c3er/.vscode/extensions/ban.spellright-3.0.122/src/spellright.js:18:18)
	at o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at activate (/Users/c3er/.vscode/extensions/ban.spellright-3.0.122/src/extension.js:19:24)
	at W.kb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:13457)
	at W.jb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:13167)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:11189
	at async o.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:6237)
	at async o.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:6200)
	at async o.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:5657)
```

**Comment by laszlo8** [comment]
Stopped working for me also for v. 1.88.0. No icon on status bar, no spellcheck.

**Comment by Ben-Voris** [comment]
Same here. 

Extension > FEATURES > Runtime Status 

Activation = `Not yet activated`

Spell Right v3.0.122 on
```text
Version: 1.88.0 (system setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by astroman68** [comment]
Linux as well...

Version: 1.88.0
Release: 24096
Commit: 0f99737786f756fe93e2a6e5d8146c46f4a53a4f
Date: 2024-04-05T12:40:21.749Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.6.25-1-MANJARO

**Comment by bartosz-antosik** [comment]
Hi! The extension binary dependencies, root cause of the above, has been updated. It took far more than usually/expected mainly because of some nasty bug in `nan` (https://github.com/nodejs/nan/issues/936#issuecomment-1961938183). Never mind, should work for now.

**Comment by rotemdan** [comment]
Thanks a lot! New version seems to be working again on `1.88.0`.
