### ISSUE TITLE
Extension fails to load in VS Code 1.90.0

### ISSUE THREAD

**Issue by reduckted** [bartosz-antosik/vscode-spellright#578]
VS Code updated to a new Electron version.
https://code.visualstudio.com/updates/v1_90#_electron-29-update

Same problem as these issues:

https://github.com/bartosz-antosik/vscode-spellright/issues/513
https://github.com/bartosz-antosik/vscode-spellright/issues/536
https://github.com/bartosz-antosik/vscode-spellright/issues/561

**Comment by rotemdan** [comment]
The extension host error log shows:

```
2024-06-06 09:56:29.973 [error] Activating extension ban.spellright failed due to an error:
2024-06-06 09:56:29.973 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\X\.vscode\extensions\ban.spellright-3.0.124\lib\bindings.js:46:25)
	at o._compile (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
	at Module.load (node:internal/modules/cjs/loader:1098:32)
	at Module._load (node:internal/modules/cjs/loader:945:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at E._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:5901)
	at n._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:30787)
	at t._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:33074)
	at Module.require (node:internal/modules/cjs/loader:1122:19)
	at h (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\X\.vscode\extensions\ban.spellright-3.0.124\src\spellright.js:18:18)
	at o._compile (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
	at Module.load (node:internal/modules/cjs/loader:1098:32)
	at Module._load (node:internal/modules/cjs/loader:945:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at E._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:5901)
	at n._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:30787)
	at t._load (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:33074)
	at Module.require (node:internal/modules/cjs/loader:1122:19)
	at h (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at activate (c:\Users\X\.vscode\extensions\ban.spellright-3.0.124\src\extension.js:19:24)
	at J.kb (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:13460)
	at J.jb (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:13173)
	at c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:11198
	at async a.n (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6361)
	at async a.m (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6324)
	at async a.l (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:5781)
```

**Comment by bartosz-antosik** [comment]
HI! Thanks @reduckted for pointing out that this is a recurring problem once Electron version gets bumped. I am working on update just there are some unexpected problems from the side of Github Actions runners. Will complete it as soon as possible.

**Comment by rotemdan** [comment]
I've updated to the new versions (`3.0.126`, `3.0.128` and `3.0.132`) as soon as they were released, and was still getting the same error. I assumed the issue wasn't fixed since it is still open.

Not that I look at the [release note for `3.0.126`](https://github.com/bartosz-antosik/vscode-spellright/blob/main/CHANGELOG.md) (6 June) it shows:

> Binaries updated for Electron 29.x.

So I'm not sure why it isn't working. My current installed version is showing `v3.0.132`.

**Comment by kmactane** [comment]
I'm getting the same problem with VS Code 1.91.0 (using Electron 29.4.0) and Spell Right 3.0.132 (the latest).

**Comment by bartosz-antosik** [comment]
Hi! Could you please tell me what OS you have the issue with?

Here is Linux working ok:

![image](https://github.com/bartosz-antosik/vscode-spellright/assets/20492548/4f318344-5742-430d-a09c-50646a3f1b4b)

**Comment by rotemdan** [comment]
My current VSCode information (Windows 11):

```
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

(`v3.0.132` still errors at startup with `Cannot read properties of null (reading 'Spellchecker')`)

**Comment by kmactane** [comment]
I'm on Windows 10. Here's the VS Code Help > About information:

```
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by reduckted** [comment]
@bartosz-antosik See #582

**Comment by Ben-Voris** [comment]
I have the same config as https://github.com/bartosz-antosik/vscode-spellright/issues/578#issuecomment-2218074138

And, other than the first frame, the stack trace is the same as https://github.com/bartosz-antosik/vscode-spellright/issues/578#issuecomment-2151749598

```text
2024-07-11 01:57:56.306 [error] Activating extension ban.spellright failed due to an error:
2024-07-11 01:57:56.306 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\X\.vscode\extensions\ban.spellright-3.0.132\lib\bindings.js:45:25)
```

**Comment by reduckted** [comment]
It might be a Windows-only problem if it works for you, @bartosz-antosik. For me on Windows, the `glob` call returns no results. #582 fixes that.

**Comment by OkkeHendriks** [comment]
Same issue here and for colleagues, me version info:

```
Version: 1.91.1 (system setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

```
2024-07-12 10:40:41.759 [error] Activating extension ban.spellright failed due to an error:
2024-07-12 10:40:41.760 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\okkhen\.vscode\extensions\ban.spellright-3.0.132\lib\bindings.js:45:25)
```

**Comment by OkkeHendriks** [comment]
Seems to be fixed in version 3.0.134.
Other version info remains equal.

**Comment by rotemdan** [comment]
`3.0.134` has started working for me on VSCode `1.91.1` (system details as I sent before), though workspace dictionary (`spellright.dict`) does not seem to work anymore. I don't remember having issues with the workspace dictionary. (I am not seeing any special errors in the log though).

---

I also tested `3.0.134` on latest VSCode insiders (`1.92.0-insider`) and the extension is not loading:

```
Version: 1.92.0-insider (user setup)
Commit: 22e3447b4b410dcf8426bf70743c5dd4030d6122
Date: 2024-07-23T05:03:52.385Z
Electron: 30.2.0
ElectronBuildId: 9884022
Chromium: 124.0.6367.243
Node.js: 20.15.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

Error:
```
TypeError: Cannot read properties of null (reading 'Spellchecker')
```

It's probably a good idea to get `1.92.0` to work as well, before it becomes stable.

**Comment by v4hn** [comment]
Same problem on current linux with vscode version:

```
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.9.7-amd64
```

```
2024-10-30 17:56:57.450 [error] Activating extension ban.spellright failed due to an error:
2024-10-30 17:56:57.450 [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
    at Object.<anonymous> (~/.vscode/extensions/ban.spellright-3.0.136/lib/bindings.js:46:25)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
...
```
